### ISSUE TITLE
Issue with dateLimit feature

### ISSUE THREAD

**Issue by jubayerarefin** [dangrossman/bootstrap-daterangepicker#1095]
I found a issue while using dateLimit feature and it is generating a warning along with few errors.

> Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Arguments: [object Object]
Error
    at Function.createFromInputFallback (http://127.0.0.1:8000/static/***/vendor/moment-with-locales.min.js:1:2532)
    at Ha (http://127.0.0.1:8000/static/***/vendor/moment-with-locales.min.js:1:13925)
    at Ga (http://127.0.0.1:8000/static/***/vendor/moment-with-locales.min.js:1:13659)
    at Fa (http://127.0.0.1:8000/static/***/vendor/moment-with-locales.min.js:1:13379)
    at Ia (http://127.0.0.1:8000/static/***/vendor/moment-with-locales.min.js:1:14102)
    at Ja (http://127.0.0.1:8000/static/***/vendor/moment-with-locales.min.js:1:14136)
    at o.lb [as isAfter] (http://127.0.0.1:8000/static/***/vendor/moment-with-locales.min.js:1:18557)
    at new DateRangePicker (http://127.0.0.1:8000/static/***/vendor/daterangepicker.js:318:73)
    at HTMLInputElement.<anonymous> (http://127.0.0.1:8000/static/***/vendor/daterangepicker.js:1535:40)
    at Function.each (http://127.0.0.1:8000/static/***/theme/js/common.js:374:23)

common.js contains jquery and sizzlejs.

Moment suggests to visit this github issue: moment/moment#1407

According to the Moment discussion it is a formatting issue.

Has anybody else noticed this and is there any workaround already implemented for this issue ?

**Comment by dangrossman** [comment]
This issue contains insufficient information to identify or reproduce a bug.

**Comment by jubayerarefin** [comment]
@dangrossman I am using the dateLimit like this

`dateLimit: {"days":30}`

and it generates the warning in the developer console.

do you need anymore information so that you can identify or reproduce this issue ?

**Comment by dangrossman** [comment]
I do not get a warning in the developer console after initializing a new date range picker with that option.

**Comment by jubayerarefin** [comment]
Using 2.1.19. I will update to latest version and see if that solves the issue.

**Comment by jubayerarefin** [comment]
Update: did not get a warning after updated to the latest version. I guess it is solved. Thanks.
