### ISSUE TITLE
Cannot set property 'daterangepicker' of undefined

### ISSUE THREAD

**Issue by aauberg** [dangrossman/bootstrap-daterangepicker#861]
I am using webpack to bundle my app. I get this error right after webpack says the bundle is VALID.
```
/home/aaron/Repos/smart-spray-portal/node_modules/react-bootstrap-daterangepicker/node_modules/bootstrap-daterangepicker/daterangepicker.js:1483
    $.fn.daterangepicker = function(options, callback) {
                         ^

TypeError: Cannot set property 'daterangepicker' of undefined
    at /home/aaron/Repos/smart-spray-portal/node_modules/react-bootstrap-daterangepicker/node_modules/bootstrap-daterangepicker/daterangepicker.js:1483:26
    at cb.parentEl (/home/aaron/Repos/smart-spray-portal/node_modules/react-bootstrap-daterangepicker/node_modules/bootstrap-daterangepicker/daterangepicker.js:28:5)
    at Object.<anonymous> (/home/aaron/Repos/smart-spray-portal/node_modules/react-bootstrap-daterangepicker/node_modules/bootstrap-daterangepicker/daterangepicker.js:35:2)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/aaron/Repos/smart-spray-portal/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```
I am not certain where to look for an answer to this issue.

**Comment by dangrossman** [comment]
I don't know anything about react or webpack. It looks like you're using a fork called "react-bootstrap-daterangepicker". That's probably a better place to ask.

**Comment by aauberg** [comment]
@dangrossman sorry about that, I did intend to post this question there. Love this datepicker btw!
